"use client";
import './globals.css';
import "./all.css";
// import { Inter } from 'next/font/google'

import NavBar from '@/lib/nav';
import Footer from '@/lib/footer';

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <body className="bg-slate-800">
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
